FROM openjdk:8-jre
MAINTAINER peepul peepvl@126.com

COPY target/base-1.0-SNAPSHOT.jar /usr/local/modules/base/base-service.jar

ENTRYPOINT ["java", "-jar","/usr/local/modules/base/base-service.jar" ]